### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by s0hogeN** [KnightOfMelons/Graduation-Project-University#1]
![Снимок экрана от 2024-06-22 14-23-13](https://github.com/KnightOfMelons/Graduation-Project-University/assets/54073660/15194fb6-8c38-4e1b-a3b6-f9a605de31e0)

http://127.0.0.1:5000/pulse_and_acceleration_characteristics

Если задавать все значения 0
![image](https://github.com/KnightOfMelons/Graduation-Project-University/assets/54073660/94c89650-b68f-4918-bf91-7c55c75b950b)

**Comment by s0hogeN** [comment]
http://127.0.0.1:5000/PID_part_1

Такая же ошибка при всех нулевых значениях

**Comment by s0hogeN** [comment]
http://127.0.0.1:5000/transfer_function_of_the_object

**Comment by KnightOfMelons** [comment]
Был установлен лимит вводимых значений (везде написал либо 0.1, либо 1, в зависимости от принимаемых значений) с помощью JS скриптов. Проделано для каждой из страниц
