### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by s0hogeN** [KnightOfMelons/Graduation-Project-University#2]
![image](https://github.com/KnightOfMelons/Graduation-Project-University/assets/54073660/e08bc5bc-500a-4540-a739-a54556f0c441)

http://127.0.0.1:5000/most_identical_transient_process

Если задавать все значения 0
![image](https://github.com/KnightOfMelons/Graduation-Project-University/assets/54073660/ffc892db-5e30-4a65-abab-e0436239fb62)

**Comment by s0hogeN** [comment]
http://127.0.0.1:5000/transient_process_using_a_PI_controller

**Comment by KnightOfMelons** [comment]
На всех элементах приема значений были выставлены ограничения в виде 0.1, 1 и 1e-7. Графики получаются в итоге ужасные, но проблему решает
