### ISSUE TITLE
У полей нет ограничения про длине

### ISSUE THREAD

**Issue by s0hogeN** [KnightOfMelons/Graduation-Project-University#4]
Смог ввести 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
ну нот нормал считаю

**Comment by s0hogeN** [comment]
Из этого следует проблема OverflowError
![image](https://github.com/KnightOfMelons/Graduation-Project-University/assets/54073660/9dcfbf67-b952-4e0e-97d2-b6d024c456ca)
http://127.0.0.1:5000/transfer_function_of_the_object

**Comment by KnightOfMelons** [comment]
Для всех основных страниц с расчётом были добавлены ограничения как с помощью стандартного HTML, так и с помощью JS скриптов
